// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTtZEJ3TxHRIjq-hUs_iVhaFowAgVRGfU',
    appId: '1:38181921976:web:12b5a884b153808c9a804d',
    messagingSenderId: '38181921976',
    projectId: 'xp-todo-app-672ff',
    authDomain: 'xp-todo-app-672ff.firebaseapp.com',
    storageBucket: 'xp-todo-app-672ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUOo_dFINQDGZqw2TfszeZcWTY0dhgUk0',
    appId: '1:38181921976:android:33219eff0639fa849a804d',
    messagingSenderId: '38181921976',
    projectId: 'xp-todo-app-672ff',
    storageBucket: 'xp-todo-app-672ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJkniwr9NXtBxMLXDeNVIZdlolUMmG71s',
    appId: '1:38181921976:ios:2c1659e11603114f9a804d',
    messagingSenderId: '38181921976',
    projectId: 'xp-todo-app-672ff',
    storageBucket: 'xp-todo-app-672ff.firebasestorage.app',
    iosBundleId: 'com.example.xpTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJkniwr9NXtBxMLXDeNVIZdlolUMmG71s',
    appId: '1:38181921976:ios:2c1659e11603114f9a804d',
    messagingSenderId: '38181921976',
    projectId: 'xp-todo-app-672ff',
    storageBucket: 'xp-todo-app-672ff.firebasestorage.app',
    iosBundleId: 'com.example.xpTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTtZEJ3TxHRIjq-hUs_iVhaFowAgVRGfU',
    appId: '1:38181921976:web:d38cae4546d050c79a804d',
    messagingSenderId: '38181921976',
    projectId: 'xp-todo-app-672ff',
    authDomain: 'xp-todo-app-672ff.firebaseapp.com',
    storageBucket: 'xp-todo-app-672ff.firebasestorage.app',
  );
}
